#!/bin/bash

source $HOME/scripts/my_fzffunctions
source $HOME/scripts/my_android_ssh
source $HOME/scripts/my_mtpfs_commands
source $HOME/scripts/my_network
source $HOME/scripts/my_mixed
source $HOME/scripts/my_tmux-mixed
source $HOME/scripts/my_khal
source $HOME/scripts/my_youtubedl


function deleterecursive() {

find . -name "*.$1" -type f

read -p "Are you sure? " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
				echo 
				echo "find . -name "*.$1" -type f -delete"
fi
}

function my_iw-disable-powersave-option-of-interface() {

sudo iw dev $1 set power_save off

}


function my_find-show-broken-links() {

find -xtype l -exec ls -l {} \;

}

function my_find-remove-broken-links() {

find . -xtype l -delete

}


function my_smartctl-get-total-usage-of-disk() {

sudo smartctl -a $1 | grep Power

}

# get the calendar week number for a specific date

my_date-get-week-number() {

date --date="$1" +"%V"

}

# 90° counterclockwise
alias my_scrcpy-horizontal="scrcpy --lock-video-orientation 1"   

# mount zip

function my_fusezip-mount() {

# fuse-zip [zip-file} [mountpoint]
fuse-zip -r $1 $2

}

function my_fusermount-unmount() {

fusermount -u $1

}

alias my_dhcpcd-edit-config="sudo vim /etc/dhcpcd.conf"

alias my_ip-address-show="ip address show"

function my_ip-addr-flush() {

# $1: interface

sudo ip addr flush dev $1

}

function my_zip-folder-recursively() {

# $1: zip name
# $2: folder to be zipped

zip -r $1 $2

}

function my_fuser-identify-processes-using-mounted-dev() {

# $1: mountpoint
fuser -mv $1

}


function my_selector() {

# show all commands and functions whose prefix is my_ or myp_ 
local choice=$({ compgen -A function; compgen -A command; } | grep '^my_\|^myp_' | sort --unique |fzf)

type $choice
echo -n $choice | xclip -selection clipboard

}

function my_pandoc-md-to-docx() {

pandoc -o $1.docx -f markdown -t docx $1.md

}

function my_pandoc-md-to-pdf() {

pandoc -o $1.pdf -f markdown -t pdf $1.md

}

function my_generate-random-string-with-following-length() {

< /dev/urandom tr -dc A-Za-z0-9_ | head -c$1

}

