#!/bin/bash

function my_phonebindportssh() {

Help()
{
cat << EOF
Name

	phonebindportssh - creates a port forward

Description

	The first instance of tcp:8022 is the local port you want to bind the remote port to. 
	The second one is the port from your Android device. Because Termux' SSHD runs on port 8022 by 
	default, this is what you want.

EOF
}


if [ "$1" == "-h" ]; then
  Help
  return 0
fi

adb forward tcp:8022 tcp:8022 
}

