#!/bin/bash

alias my_journalctl-verify-logs="journalctl --verify"

alias my_journalctl-clear-logs="sudo journalctl --vacuum-size=120M"

alias my_journalctl-disk-usage-logs="journalctl --disk-usage"


alias my_upower-list-path-of-avail-devs="upower -e"
alias my_upower-show-dev-infos="upower -i"




