#!/bin/bash

function bring-interface-down() {

  sudo ip link set dev $1 down 

}

function bring-interface-up() {

  sudo ip link set dev $1 up 

}

function my_show-used-dns() {

cat /etc/resolv.conf

}

function my_chattr-make-resolv-immutable() {

sudo chattr +i /etc/resolv.conf

}

function my_chattr-make-resolv-mutable() {

sudo chattr -i /etc/resolv.conf

}

function my_ufw-status-verbose(){

sudo ufw status verbose

}

function my_ufw-status-numbered(){

sudo ufw status numbered

}

function my_ufw-delete-rule() {

# $1: number

sudo ufw delete $1

}

function my_ufw-logging-off() {

sudo ufw logging off

}

function my_ufw-logging-low() {

sudo ufw logging low

}

function my_ufw-dmesg() {

dmesg -T --color=always | grep UFW --color=always

}


function my_ufw-disable() {

sudo ufw disable

}

function my_ufw-enable() {

sudo ufw enable

}


function my_arpscan-show-devices-lan-for-interface() {

sudo arp-scan --interface=$1 --localnet

}

function my_nmap-scan-dev-for-open-ports() {
# -sT:  scan for TCP ports 
# -p-:   scan for all 65535 ports
sudo nmap --stats-every 10s -sT -p- $1
}


function my_curl-get-public-ip-through-web-request() {

curl https://ipinfo.io/ip

}

function my_dig-get-public-ip-through-dns-request() {

dig +short myip.opendns.com @resolver1.opendns.com

}

function my_vnstat-list-all-interfaces() {

vnstat --iflist

}

# Query the network traffic:
function my_vnstat-query-network-traffic() {
  
 vnstat --query
}


# View live network traffic usage
function my_vnstat-live-network-traffic-usage() {

vnstat --live

}


# Output of summary for an interface
function my_vnstati-output-summary-for-interface() {
# $1: interface name
vnstati -s -i $1 -o "$(date +%Y-%m-%dT%H:%M:%S)_vnstati-summary.png"
}

# Output of hourly stats for an interface
function my_vnstati-output-hourly-stats-for-interface() {
# $1: interface name
vnstati -h -i $1 -o "$(date +%Y-%m-%dT%H:%M:%S)_vnstati-summary.png"
}

# Monthly statistics
function my_vnstat-monthly-statistics-for-interface() {
vnstat -m -i $1
}

# hourly statistics
function my_vnstat-monthly-statistics-for-interface() {
vnstat -h -i $1
}

# hourly statistics
function my_vnstat-output-summary-for-interface() {
vnstat -h -s $1
}
