#!/bin/bash

function bring-interface-down() {

  sudo ip link set dev $1 down 

}

function bring-interface-up() {

  sudo ip link set dev $1 up 

}

function my_show-used-dns() {

cat /etc/resolv.conf

}

function my_chattr-make-resolv-immutable() {

sudo chattr +i /etc/resolv.conf

}

function my_chattr-make-resolv-mutable() {

sudo chattr -i /etc/resolv.conf

}

function my_ufw-status-verbose(){

sudo ufw status verbose

}

function my_ufw-status-numbered(){

sudo ufw status numbered

}

function my_ufw-delete-rule() {

# $1: number

sudo ufw delete $1

}

function my_ufw-logging-off() {

sudo ufw logging off

}

function my_ufw-logging-low() {

sudo ufw logging low

}

function my_ufw-dmesg() {

dmesg -T --color=always | grep UFW --color=always

}


function my_ufw-disable() {

sudo ufw disable

}

function my_ufw-enable() {

sudo ufw enable

}


function my_arpscan-show-devices-lan() {

sudo arp-scan --interface=wlp36s0b1 --localnet

}

function my_nmap-scan-dev-for-open-ports() {
# -sT:  scan for TCP ports 
# -p-:   scan for all 65535 ports
sudo nmap --stats-every 10s -sT -p- $1
}


function my_curl-get-public-ip-through-web-request() {

curl https://ipinfo.io/ip

}

function my_dig-get-public-ip-through-dns-request() {

dig +short myip.opendns.com @resolver1.opendns.com

}

