#!/usr/bin/env sh

source /home/meyya/scripts/my_fzffunctions
source /home/meyya/scripts/my_android_ssh
source /home/meyya/scripts/my_mtpfs_commands
source /home/meyya/scripts/my_network
source /home/meyya/scripts/my_mixed
source /home/meyya/scripts/my_tmux-mixed

function deleterecursive() {

find . -name "*.$1" -type f

read -p "Are you sure? " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
				echo 
				echo "find . -name "*.$1" -type f -delete"
fi
}

function my_iw-disable-powersave-option-of-interface() {

sudo iw dev $1 set power_save off

}

alias my_youtubedl-download-mp3="youtube-dl --extract-audio --audio-format mp3"


function my_find-show-broken-links() {

find -xtype l -exec ls -l {} \;

}

function my_find-remove-broken-links() {

find . -xtype l -delete

}
