#!/bin/bash

alias my_tmux-new-session-with-following-name="tmux new -s"
alias my_tn="tmux new -s"

alias my_tmux-attach-to-session="tmux attach-session -t"
alias my_ta="tmux attach-session -t"
alias my_tam="tmux attach-session -t main"




alias my_tmux-kill-session="tmux kill-session -t"


alias my_tl="tmux ls"
