#!/usr/bin/env sh

source /home/meyya/scripts/fzffunctions
source /home/meyya/scripts/android_ssh
source /home/meyya/scripts/tmux_aliases
source /home/meyya/scripts/mtpfs_commands


function deleterecursive() {

find . -name "*.$1" -type f

read -p "Are you sure? " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
				echo 
				echo "find . -name "*.$1" -type f -delete"
fi
}

