#!/usr/bin/env sh

source /home/meyya/scripts/my_fzffunctions
source /home/meyya/scripts/my_android_ssh
source /home/meyya/scripts/my_mtpfs_commands
source /home/meyya/scripts/my_network
source /home/meyya/scripts/my_mixed


function deleterecursive() {

find . -name "*.$1" -type f

read -p "Are you sure? " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
				echo 
				echo "find . -name "*.$1" -type f -delete"
fi
}

function disable-dev-powersave() {

sudo iw dev $1 set power_save off

}

