#!/bin/bash
# temporary function for setting Power Management feature of hdd

drive="$(blkid | grep "p_arch_swap" | cut -c1-8;)" # get current disk name
COMMAND="sudo hdparm -B 254 ${drive}"

echo "Perform the following command: ${COMMAND}"
echo -n "Answer 'yes' or 'no': "

read REPLY
if [[ $REPLY == "y" ]]; then
     $COMMAND
 else
     echo Aborted
fi
